jmxexporter-prometheus-grafana/assets/prometheus/prometheus-config/prometheus.yml, jmxexporter-prometheus-grafana/start.sh, utils/setup_cp_demo.sh
This PR removes realpath dependency by using a bash native function doing the same job.
It also add some buffer on scrape_timeout so we can scrape more easily.
To get some background the first time prometheus will fetch the metric it will need to evaluate all jmx-metrics and compile the regexp which can be a CPU hit at first.
Because cp-demo is throttling cpu with the "cpu: 0.7" directive in the docker-compose it's not able answer fast enough with the default prometheus scrape timeout (10s).
Here we just increased the buffer to leave time to fetch (in particular for the first time)
=> Getrid of realpath

jmxexporter-prometheus-grafana/assets/prometheus/grafana/provisioning/dashboards/connect.json, jmxexporter-prometheus-grafana/assets/prometheus/jmx-exporter/kafka-connect.yml, jmxexporter-prometheus-grafana/assets/prometheus/prometheus-config/prometheus.yml, jmxexporter-prometheus-grafana/docker-compose.override.yml
This PR adds Kafka Connect Grafana dashboard:
Example:
=> Add Kafka Connect Grafana dashboard

jmxexporter-prometheus-grafana/assets/prometheus/grafana/provisioning/dashboards/zookeeper-overview.json
Zookeeper dashboard datasource is empty, and points to default ds. This won't work on Grafana deployments where there are other default datasources.
=> Set Zookeeper Grafana dashboard datasource to Prometheus

jmxexporter-prometheus-grafana/docker-compose.override.yml, jolokia-elastic-kibana/docker-compose.override.yml
This patch is to resolve issues with the "address in use" problem arising due to recent changes in the cp-demo package. 
Recent changes in cp-demo moved the topic creation script from additional containers to Kafka containers which would not allow CLI execution as these tools will reference the KAFKA_OPTS and try instrumenting JMX exporter/Jolokia on the same port already used. 
The fix moves the -javaagent switch from KAFKA_OPTS to EXTRA_ARGS to prevent those issues.
=> Convert KAFKA_OPTS to EXTRA_ARGS to allow kafka cli compatibility

jmxexporter-prometheus-grafana/assets/prometheus/grafana/provisioning/dashboards/kafka-overview.json, jmxexporter-prometheus-grafana/assets/prometheus/jmx-exporter/kafka_broker.yml
Hey folks, 
In this PR we collect more metrics on broker side (socket server metrics, but also consumer group coordinator).
We also bring some changes on kafka overview dashboard :
- ProducerRequest rate was not properly filtered
- Add TotalRequest rate
- Add producer/fetch request per topic (will help performance troubleshooting)
- Add nb consumer group metrics
- Add connections metrics
- Add filter by topic
- All graphs hover are now sorted decreasing (makes things much more readable)
- Converted legacy single value widget into stat plugin (the old one is deprecated)
- Stat plugin should display last value instead of a mean.
- Add replication graphs over time
- Dashboard auto-refresh of 1m
=> Prometheus broker refactoring

jmxexporter-prometheus-grafana/assets/prometheus/grafana/provisioning/dashboards/connect-overview.json
This PR added a missing `instance` label in Kafka Connect dashboard.
=> Add missing instance label

shared-assets/jmx-exporter/kafka_broker.yml
The current JMX metrics rules for Kafka Broker were pretty stale and were not performing optimally. Removed all the greedy searches and moved them to a better word based search for ease of rule execution and about 100% lower parsing time.
=> Metrics Fetch Optimization for Kafka Broker

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-overview.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-topics.json
Changes:
- Update topics dashboard with log size and requests per second.
- Update cluster dashboard with same intervals, better default range, request metrics on top and more.
Replaces #24
=> Update to Kafka cluster and topics dashboards

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/zookeeper-overview.json
By default znodes are around ~800. Stats by default add a threshold of 80.
This gives the impression that something is wrong when it's actually normal.
=> Zookeeper dashboard: remove znodes thresholds

.gitignore, README.md, jmxexporter-prometheus-grafana/docker-compose.override.yml, jmxexporter-prometheus-grafana/start.sh
Kafka Lag Exporter is failing when using a newer JDK version to run the demo: https://github.com/lightbend/kafka-lag-exporter/issues/270
Adding this limitation to the docs, and adjusted some directories.
=> MINOR: Updating docs with Keystore limitations (JDK8)

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-consumer.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-producer.json, jmxexporter-prometheus-grafana/assets/prometheus/prometheus-config/prometheus.yml
Fix #42 
Changes:
- Update dashboards to latest Grafana.
- Remove job filter to capture all producers/consumers.
- Add hostname label for filtering.
Producer dashboard:
Consumer dashboard:
=> feat: update client dashboards

jmxexporter-prometheus-grafana/docker-compose.override.yml
Also described in https://confluentinc.atlassian.net/browse/DEVX-2690
Trailling slashes in volume-mount configurations in docker-compose `yml` make the configs incompatible with Docker on Windows/WSL. 
Implemented FIX:
Remove trailing slashes from volume mount configs in `docker-compose.override.yml`
Reviewers:
Please double check that this doesn't break on Linux/MacOS
=> fix: devx-2690 remove volume mount trailing slashes

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-quotas.json
The units on several graphs in the quotas Grafana dashboard were not appropriate.
This has been corrected.
=> Fixing incorrect units on quota dashboard

ccloud-prometheus-grafana/start.sh
This PR resolves #83 
Explicitly creating the directory `$MONITORING_STACK/assets/prometheus/prometheus-config/` using `mkdir -p` creates the directory with in the user context witht the right owner/mode.
Calling `mkdir -p` on an existing directory does nothing, so I believe it is safe for use in a newly cloned repo, as well as in a re-use scenario, where /prometheus/prometheus-config/ already exists.
=> Explicit mkdir prevents permissions block

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-cluster.json
It can be useful to have a quick view on how many leaders we have for each broker.
=> Adding leader count panel to Graphana Kafka Cluster dashboard

shared-assets/jmx-exporter/kafka_broker.yml, shared-assets/jmx-exporter/kafka_broker_p99only.yml
See also: https://github.com/confluentinc/cp-ansible/pull/1304
Has four changes:
* Move the more-specific rule containing 'type,name,clientId,topic,partition' ABOVE less-specific rule containing 'type,name,topic,partition' so that clientId is properly parsed as a separate capture group (rather than as part of the name). This initially resulted in the 'name' capture group looking something like this: 'ConsumerLag, clientId=ReplicaFetcherThread-0-103-Default'
* Creates a duplicate of the rule capturing 'type, name, clientId, brokerHost, brokerPort', but with a Count instead of Value
* Create two additional rules capturing arbitrary key-value pairs when there are 6 and 5 arbitrary pairs (in front of the rule capturing 4 arbitrary pairs
Sample problematic JMX / Prometheus metrics:
Original: …
=> Fix JMX Exporter rules

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-topics.json
problem related to `kafka_log_log_logendoffset` and `kafka_log_log_logstartoffset` panels where panels don't work as the query returns no data because expression try to match topic name to the list of topics
fixed it by using `=~` regex matches operator instead of  `=`exactly equal operator
=> fixed expression in Topic offsets  row

ccloud-prometheus-grafana/assets/grafana/provisioning/dashboards/ccloud.json
Fixes https://github.com/confluentinc/jmx-monitoring-stacks/issues/108
Proposed state is below. adding consumer lag offsets on the 4th row within the `Global` section.
| Previous State | Proposed State |
|--|--|
| ![Screenshot 2023-06-22 at 18 40 54](https://github.com/confluentinc/jmx-monitoring-stacks/assets/6927131/4581ce4c-0f1b-45e0-9be3-42c82c8ba599)  | ![Screenshot 2023-06-22 at 18 41 05](https://github.com/confluentinc/jmx-monitoring-stacks/assets/6927131/c3fe1843-81de-4c48-a760-394ed13a6ab4) |
=> support consumer lag offset from confluent cloud

ccloud-prometheus-grafana/assets/grafana/provisioning/dashboards/ccloud.json
**Why**
The text shown in dashboard is an incorrect representation of schema registry instances. The number of instances is not exposed to the outside world. [reference][1] However, the metrics used refers to the total number of schemas. [source][3]
**Expected**
The text should be `Total Schemas`
**Observed**
The text is `Total Schema Registry Instances`
**Reproduce Steps**
1. setup prometheus
1. setup grafana
1. create confluent cloud dashboard from [7.2-post][2]
1. Notice the total schema registry instances shows 
**Changes**
| Before | After |
|--|--|
|  ![Screenshot 2023-09-27 at 13 53 32](https://github.com/confluentinc/jmx-monitoring-stacks/assets/6927131/19e4be35-7ad2-41e2-87f3-da730f8f1a05)  | ![Screenshot 2023-09-27 at 13 54 …
=> Correctly use Total Schemas

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-connect-cluster.json
**Why**
If the env and cluster ID are specified in Prometheus metric collection config, the metrics do not show up properly in Grafana.
**Expected**
The variables should be set dynamically from the available metrics.
**Reproduce Steps**
1. Set up Kafka Connector with [this JMX exporter][1]
2. Create a prometheus file with this configuration
```sh
- job_name: "kafka-connect"
sample_limit: 10000
scrape_interval: 1m
scrape_timeout: 55s
honor_timestamps: true
static_configs:
- targets:
- connect-0.connect.confluent.svc.cluster.local:7778
- connect-1.connect.confluent.svc.cluster.local:7778
labels:
env: "prod"
kafka_connect_cluster_id: "mycluster"
scheme: http
metrics_path: /metrics
relabel_configs:
- source_labels: [__address__]
target_label: hostname
regex: '([^:]+)(:[0-9]+)?'
replacement: …
```
=> Correctly populate Grafana variables in Kafka Connect dashboard

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/confluent-oracle-cdc.json, shared-assets/jmx-exporter/kafka_connect.yml
Initial implementation of Oracle CDC dashboard.
multiple CDC connectors:
To test:
run playground [example](https://github.com/vdesabou/kafka-docker-playground/tree/master/connect/connect-cdc-oracle19-source) using `--enable-jmx-grafana`:
```
playground run -f cdc-oracle19-cdb-table<tab> --enable-jmx-grafana
```
=> Oracle CDC Connector metrics #128

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-connect-cluster.json
Rebalance metrics do not show since the job name is `connect` instead of `kafka-connect`.
| Before | After |
|--|--|
| ![Screenshot 2023-10-23 at 19 12 29](https://github.com/confluentinc/jmx-monitoring-stacks/assets/6927131/dc66ac6e-9fc9-4c7f-82db-975024da0d51) |  ![Screenshot 2023-10-23 at 19 12 22](https://github.com/confluentinc/jmx-monitoring-stacks/assets/6927131/716c04d0-9903-4782-9b5b-44bb3ec39b13)
=> Rebalance metrics should be job=kafka-connect

shared-assets/jmx-exporter/kafka_connect.yml
**Why**
Using `cache: true` can make some JMX values show up like this: `<cache>` in the HTTP endpoint, causing the dashboard to not show up correctly.
**Expected**
It should not break dashboard by retrieving correct values.
[no-cache-kafka-connect-jmx.txt](https://github.com/confluentinc/jmx-monitoring-stacks/files/13069755/no-cache-kafka-connect-jmx.txt)
**Observed**
It breaks dashboard by retrieving `<cache>` values.
[cached-kafka-connect-jmx.txt](https://github.com/confluentinc/jmx-monitoring-stacks/files/13069754/cached-kafka-connect-jmx.txt)
=> Don't use cache in kafka connect jmx exporter

ccloud-prometheus-grafana/assets/grafana/provisioning/dashboards/ccloud.json
**Why**
Fix prometheus datasource so that they all have the same source. Without this, it initially doesn't show all widgets.
**Expected**
It should show widgets based on one datasource, `Prometheus`.
**Observed**
It doesn't show some widgets because datasource is fixed to a uid.
=> Set explicit prometheus datasource and remove uid

ccloud-prometheus-grafana/assets/grafana/provisioning/dashboards/ccloud.json
| Item | Changes |
|--|--|
| Write on Topics | Change from Graph widget to Stats (since graph exists below and total ingress/sec doesn't exist) |
| Read on Topics | Change from Graph widget to Stats (since graph exists below and total egress/sec doesn't exist)  |
| Request (rate) | Change title to `Request Count (rate)` from `Request (rate)` |
**Before**
**After**
=> Summarize ingress and egress at the top in Confluent Cloud dashboard

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/zookeeper-cluster.json
remove zookeeper_ticktime  since in version 3.3  (zk )and above the value of the request is in ms 
https://github.com/apache/zookeeper/blob/master/zookeeper-server/src/main/java/org/apache/zookeeper/server/Stats.java#L40-L51
we can probably backport to all dashboards since version 6 
https://docs.confluent.io/platform/current/installation/versions-interoperability.html#zk
=> remove zookeeper_ticktime 

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/confluent-platform.json
Looks like someone swapped null for the datasource of the vars causing them not to be pulled
=> Update confluent-platform.json with correct datasource for vars

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/confluent-platform.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-cluster.json
Added 3 new tabs:
1 - Metrics for Fetch Session - https://cwiki.apache.org/confluence/display/KAFKA/KIP-227%3A+Introduce+Incremental+FetchRequests+to+Increase+Partition+Scalability
2 - Metrics for Metadata Request
3 - Metrics for Replicas - https://docs.confluent.io/platform/current/kafka/post-deployment.html#lagging-replicas
=> Adding new metrics to Kafka cluster: Fix #194 Fix #195 Fix #196

ccloud-prometheus-grafana/.gitignore, ccloud-prometheus-grafana/utils/docker-compose-template.yaml
The main point of this PR is to bump the Grafana version of the CC Prometheus / Grafana module.
The current one contains some issues preventing panels to be refreshed properly.
I have added a specific ".gitignore" file for generated resources as well, and we need to specify the platform for the cost exporter on MacOS.
=> [CC prom/grafana] Bump grafana version and small other improvements

ccloud-prometheus-grafana/assets/grafana/provisioning/dashboards/ccloud-ksql.json
I created a Grafana dashboard for monitoring the query saturation and disk utilisation per persistent query during a recent PS engagement. Open sourcing it for the wider community.
=> Add grafana dashboard for ccloud ksql

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-consumer.json
The consumer dashboard of the Prometheus/Grafana module uses a metric exported by the Consumer Lag Exporter tool.
This tool is now more or less deprecated, and we already have a dedicated dashboard for the Lag exporter.
Instead, it should use the new metric `kafka_server_tenant_metrics_consumer_lag_offsets`.
I have removed the client id in the Prometheus query as well because the client id in this metric is different from the client id retrieved using the metric `kafka_consumer_app_info`.
=> Fix: Prometheus/Grafana consumer lag group id retrieval should not use lag exporter metric

.gitpod.yml, README.md
Related to this issue https://github.com/confluentinc/jmx-monitoring-stacks/issues/234, will enable Gitpod by starting dev-toolkit instead cp-demo.
=> Gitpod Support

jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-consumer.json
Fix #252 
Provided retro compatibility with lag exporter and enhanced the method to export variables:
- Client ID
- Group ID
- Instance
=> Fix Issue 252 - Kafka Consumer dashboard - cli consumer are not reported in client-id select box Variable

README.md, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/confluent-audit.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-cluster.json
This PR contains fix for:
- Fix #266 
- Fix #267 
- It also add two more metrics for stray partitions:
-- kafka_server_replicamanager_straypartitionstotalsize
-- kafka_server_replicamanager_straypartitionsmisclassifiedcount
How to test the PR:
- run _dev-toolkit_ default profile with _start.sh_
- verify that the issues have been resolved in: 
Dashboard: Grafana --> Kafka Cluster
=> Kafka Cluster - Fix/grafana dashboard

jmxexporter-prometheus-grafana/cfk/pm-confluent.yaml
This ensures that the target labels will be in the Prometheus metrics, 
which are needed for the dashboards.
Also adds a newline at the end of the file
=> Add missing podTargetLabels to prometheusExporter

README.md, dev-toolkit/start.sh, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/confluent-platform-kraft.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-cluster-kraft.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kafka-topics-kraft.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/kraft.json
This PR aims to revisit KRaft dashboards, used at the moment in dev-toolkit (in the future I suppose they will be used also for cp-demo)
Fix #277 #278 #279
=> revisiting KRaft grafana - dashboards - Fix #277 #278 #279

jmxexporter-prometheus-grafana/README.md, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/cluster-linking.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/confluent-audit.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/confluent-oracle-cdc.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/confluent-platform-kraft.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/confluent-platform.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/confluent-rbac.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/dashboard.yml, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/debezium-connectors.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-cluster-kraft.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-cluster.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-connect-cluster.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-consumer.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-lag-exporter.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-producer.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-quotas.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-stream.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-streams-rocksdb.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-topics-kraft.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-topics.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kafka-transaction-coordinator.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/kraft.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/ksqldb-cluster.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/librdkafka-application.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/mongo.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/replicator.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/rest-proxy.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/schema-registry-cluster.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/tiered-storage.json, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter/zookeeper-cluster.json
This PR adds old grafana dashboards compatible with JMX Exporter < 1.x
Grafana dashboards are supported for JMX Exporter version 1.x.
If you still use JMX Exporter version < 1.x (example 0.20), you would need to use the dashboards from this folder: [grafana-dashboards-exporter-pre-1.x](https://github.com/confluentinc/jmx-monitoring-stacks/blob/main/jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards-old-exporter)
=> add grafana dashboards compatible with jmx exporter < 1.x

README.md, dev-toolkit/connect/connector_datagen.json, dev-toolkit/connect/connector_filesink.json, dev-toolkit/docker-compose.connect.yaml, dev-toolkit/start.sh, dev-toolkit/stop.sh, jmxexporter-prometheus-grafana/README.md
Adding a _connect_ profile for dev-toolkit
How to test:
1.  Run dev-toolkit with command: 
_./start.sh --profile connect_
It will deploy a datagen source connector and a file sink connector as samples.
This PR contributes to #261
=> adding kafka connect profile to dev-toolkit - #261

dev-toolkit/docker-compose.tieredstorage.yaml, dev-toolkit/start.sh, dev-toolkit/stop.sh, dev-toolkit/tieredstorage/minio.properties, jmxexporter-prometheus-grafana/README.md, jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/tiered-storage.json
To test, use **devtoolkit**:
```bash
$ cd dev-toolkit
$ start.sh --profile tieredstorage
```
It uses a bucket named _democp-bucket_ hosted on local _minio_ instance, started as a docker container.
topic _trades_ has been created using:
```bash
--config confluent.tier.enable=true --config confluent.tier.local.hotset.ms=30000  --config segment.bytes=2000000
```
Part of issue: #261
=> add Confluent Tiered Storage profile to dev-toolkit
